export default {
    PAGES_RECEIVED: 'PAGES_RECEIVED',

    PAGES_ITEM_RECEIVED: 'PAGES_ITEM_RECEIVED',
    PAGE_ITEM_SUBMIT: 'PAGE_ITEM_SUBMIT',
    PAGES_FILTER_BY: 'PAGES_FILTER_BY',

    PAGE_RECEIVED: 'PAGE_RECEIVED',
    PAGE_SET_TITLE: 'PAGE_SET_TITLE',
    PAGE_SET_FIELD_BY_ID: 'PAGE_SET_FIELD_BY_ID',

    SET_USER_TOKEN: 'SET_USER_TOKEN',
    UNSET_USER_TOKEN: 'UNSET_USER_TOKEN',
    CURRENT_USER: 'CURRENT_USER',
    ADD_STEPS_ACCOUNT: 'ADD_STEPS_ACCOUNT',


}