export default {
    PAGES_RECEIVED: 'PAGES_RECEIVED',

    PAGES_ITEM_RECEIVED: 'PAGES_ITEM_RECEIVED',
    PAGE_ITEM_SUBMIT: 'PAGE_ITEM_SUBMIT',
    PAGES_FILTER_BY: 'PAGES_FILTER_BY',

    PAGE_RECEIVED: 'PAGE_RECEIVED',
    PAGE_SET_TITLE: 'PAGE_SET_TITLE',
    PAGE_SET_STATUS: 'PAGE_SET_STATUS',
    PAGE_SET_FIELD_BY_ID: 'PAGE_SET_FIELD_BY_ID',

    SET_USER_TOKEN: 'SET_USER_TOKEN',
    UNSET_USER_TOKEN: 'UNSET_USER_TOKEN',
    CURRENT_USER: 'CURRENT_USER',
    ADD_STEPS_ACCOUNT: 'ADD_STEPS_ACCOUNT',

    GET_SCHEMA_BY_ID: 'GET_SCHEMA_BY_ID',
    SET_NEW_FIELDS_TO_SCHEMA: 'SET_NEW_FIELDS_TO_SCHEMA',
    EDIT_SCHEMA_FIELD: 'EDIT_SCHEMA_FIELD',


    GET_ALL_MEDIA: 'GET_ALL_MEDIA',

    SET_POST_TYPE: 'SET_POST_TYPE',
    SET_POST_BY_TYPE: 'SET_POST_BY_TYPE',
    SET_NEW_POST_TYPE: 'SET_NEW_POST_TYPE',
    SAVE_POST_TYPE_BY_ID: 'SAVE_POST_TYPE_BY_ID',

    GET_CURRENT_MENU: 'GET_CURRENT_MENU',
    ADD_ITEM_TO_MENU: 'ADD_ITEM_TO_MENU',
    REORDER_CURRENT_MENU: 'REORDER_CURRENT_MENU',
    GET_ALL_MENU_TYPES: 'GET_ALL_MENU_TYPES',
}